package duke;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import duke.exceptions.CannotFindTaskException;
import duke.exceptions.CannotSortException;
import duke.exceptions.NoMatchingKeywordException;
import duke.exceptions.TaskMarkedException;
import duke.exceptions.TaskUnmarkedException;

/**
 * Represents a list of tasks generated by user.
 * A <code>TaskList</code> object corresponds to
 * a collection of Task
 */
public class TaskList {

    private ArrayList<Task> taskList;

    /**
     * Creates a taskList that can hold
     * size of 100 tasks.
     */
    public TaskList() {
        this.taskList = new ArrayList<>(100);
    }

    /**
     * Creates a taskList from an existing list of task.
     */
    public TaskList(List<? extends Task> taskList) {
        this.taskList = new ArrayList<>(taskList);
    }

    /**
     * Adds task to the taskList
     *
     * @param task target task to be added to taskList.
     */
    public void addTask(Task task) {
        this.taskList.add(task);
    }

    /**
     * Returns a taskList that fits the target keyword.
     *
     * @param keyword target keyword.
     * @return taskList.
     * @throws NoMatchingKeywordException If no task matches keyword.
     */
    public TaskList findTask(String keyword) throws NoMatchingKeywordException {
        assert !keyword.isBlank() : "keyword should not be blank";
        List<Task> filtered = this.taskList.stream()
                .filter(task -> task.isMatchKeyword(keyword))
                .collect(Collectors.toList());
        TaskList filteredTaskList = new TaskList(filtered);

        if (filteredTaskList.size() == 0) {
            throw new NoMatchingKeywordException(keyword);
        }
        return new TaskList(filtered);
    }

    /**
     * Returns list of deadlines sorted in chronological order.
     *
     * @param order decreasing or increasing order.
     * @return TaskList.
     */
    public TaskList sortDeadlineChronologically(Order order) {
        Comparator<Deadline> deadlineComparator = (d1, d2) ->
                d1.compareChronologically(d2);

        Stream<Deadline> deadlineStream = taskList
                .stream()
                .filter(task -> task instanceof Deadline)
                .map(task -> (Deadline) task);
        if (order == Order.decreasing) {
            List<Deadline> result = deadlineStream
                    .sorted(deadlineComparator.reversed())
                    .collect(Collectors.toList());
            return new TaskList(result);
        }
        List<Deadline> result = deadlineStream
                .sorted(deadlineComparator)
                .collect(Collectors.toList());
        return new TaskList(result);
    }

    /**
     * Returns list of deadlines sorted in lexicographical order.
     *
     * @param order decreasing or increasing order.
     * @return TaskList.
     */
    public TaskList sortDeadlineLexicographically(Order order) {
        Comparator<Deadline> deadlineComparator = (d1, d2) ->
                d1.compareLexicographically(d2);
        Stream<Deadline> deadlineStream = taskList.stream()
                .filter(task -> task instanceof Deadline)
                .map(task -> (Deadline) task);
        if (order == Order.increasing) {
            List<Deadline> result = deadlineStream
                    .sorted(deadlineComparator.reversed())
                    .collect(Collectors.toList());
            return new TaskList(result);
        }
        List<Task> result = deadlineStream
                .sorted(deadlineComparator)
                .collect(Collectors.toList());
        return new TaskList(result);
    }

    /**
     * Returns list of events sorted in chronological order.
     *
     * @param order decreasing or increasing order.
     * @return TaskList.
     */
    public TaskList sortEventChronologically(Order order) {
        Comparator<Event> eventComparator = (e1, e2) ->
                e1.compareChronologically(e2);

        Stream<Event> eventStream = taskList
                .stream()
                .filter(task -> task instanceof Event)
                .map(task -> (Event) task);
        if (order == Order.decreasing) {
            List<Event> result = eventStream
                    .sorted(eventComparator.reversed())
                    .collect(Collectors.toList());
            return new TaskList(result);
        }
        List<Event> result = eventStream
                .sorted(eventComparator)
                .collect(Collectors.toList());
        return new TaskList(result);
    }

    /**
     * Returns list of events sorted in lexicographical order.
     *
     * @param order decreasing or increasing order.
     * @return TaskList.
     */
    public TaskList sortEventLexicographically(Order order) {
        Comparator<Event> eventComparator = (e1, e2) ->
                e1.compareLexicographically(e2);
        Stream<Event> eventStream = taskList.stream()
                .filter(task -> task instanceof Event)
                .map(task -> (Event) task);
        if (order == Order.increasing) {
            List<Event> result = eventStream
                    .sorted(eventComparator.reversed())
                    .collect(Collectors.toList());
            return new TaskList(result);
        }
        List<Task> result = eventStream
                .sorted(eventComparator)
                .collect(Collectors.toList());
        return new TaskList(result);
    }

    /**
     * Returns list of deadlines or events
     * sorted in lexicographical order.
     * @param typeOfTask deadline or event.
     * @param order decreasing or increasing order.
     * @return TaskList.
     * @throws CannotSortException if taskList cannot be sorted.
     */
    public TaskList sortLexicographically(
            TypeOfTask typeOfTask,
            Order order)
            throws CannotSortException {
        if (typeOfTask == TypeOfTask.deadline) {
            return sortDeadlineLexicographically(order);
        }
        if (typeOfTask == TypeOfTask.event) {
            return sortEventLexicographically(order);
        }
        throw new CannotSortException("CANNOT SORT TODO LEXICOGRAPHICALLY");
    }

    /**
     * Returns list of deadlines or events
     * sorted in chronological order.
     * @param typeOfTask deadline or event.
     * @param order decreasing or increasing order.
     * @return TaskList.
     * @throws CannotSortException if taskList cannot be sorted.
     */
    public TaskList sortChronologically(
            TypeOfTask typeOfTask,
            Order order)
            throws CannotSortException {
        if (typeOfTask == TypeOfTask.deadline) {
            return sortDeadlineChronologically(order);
        }
        if (typeOfTask == TypeOfTask.event) {
            return sortEventChronologically(order);
        }
        throw new CannotSortException("CANNOT SORT TODO CHRONOLOGICALLY");
    }

    /**
     * Returns a task that gets marked.
     *
     * @param task target task.
     * @return Task.
     * @throws TaskMarkedException if target task already marked.
     * @throws CannotFindTaskException if target task cannot be found.
     */
    public Task markStatus(int task) throws TaskMarkedException, CannotFindTaskException {
        assert task >= 0 : "task index should be more than or equal to 0";
        try {
            Task curr = taskList.get(task - 1);
            if (curr.isDone()) {
                throw new TaskMarkedException(task);
            }
            curr.toggleStatus();
            return curr;
        } catch (IndexOutOfBoundsException e) {
            throw new CannotFindTaskException();
        }
    }

    /**
     * Returns a task to get unmarked.
     *
     * @param task target task.
     * @return Task.
     * @throws TaskUnmarkedException if target task already unmarked.
     * @throws CannotFindTaskException if target task cannot be found.
     */
    public Task unmarkStatus(int task) throws TaskUnmarkedException, CannotFindTaskException {
        assert task >= 0 : "task index should be more than or equal to 0";
        try {
            Task curr = taskList.get(task - 1);
            if (!curr.isDone()) {
                throw new TaskUnmarkedException(task);
            }
            curr.toggleStatus();
            return curr;
        } catch (IndexOutOfBoundsException e) {
            throw new CannotFindTaskException();
        }
    }

    /**
     * Find target task and delete it.
     * Return task that is deleted.
     *
     * @param task index of task
     * @return Task.
     */
    public Task deleteTask(int task) throws CannotFindTaskException {
        assert task >= 0 : "task index should be more than or equal to 0";
        try {
            Task curr = taskList.get(task - 1);
            taskList.remove(task - 1);
            return curr;
        } catch (IndexOutOfBoundsException e) {
            throw new CannotFindTaskException();
        }
    }

    /**
     * Returns string representation of TaskList.
     *
     * @return String.
     */
    @Override
    public String toString() {
        String result = "";
        Object[] taskArr = this.taskList.toArray();
        for (int i = 0; i < this.taskList.size(); i++) {
            result += (i + 1)
                    + ". "
                    + taskArr[i].toString()
                    + "\n";
        }
        return result;
    }

    /**
     * Returns int size of taskList.
     *
     * @return int.
     */
    public int size() {
        return taskList.size();
    }

    /**
     * Returns int size of taskList with greetings.
     *
     * @return String.
     */
    public String numOfTask() {
        if (taskList.size() > 1) {
            return "YOU HAVE "
                    + taskList.size()
                    + " TASKS!";
        } else {
            return "YOU HAVE "
                    + taskList.size()
                    + " TASK!";
        }
    }

    /**
     * Returns compact String representation
     * of taskList
     *
     * @return String.
     */
    public String generateSave() {
        String result = taskList
                .stream()
                .map(task -> task.toSaveVersion())
                .reduce("", (res, task) -> res + task);
        return result;
    }
}
